import { WorksheetData } from './excel-manager.js';

export class ProfessionalTemplates {
  
  static createNPVAnalysisWorksheet(projectName: string, discountRate: number): WorksheetData {
    return {
      name: 'NPV Analysis',
      data: [
        ['NPV ANALYSIS - ' + projectName.toUpperCase(), '', '', '', '', ''],
        ['Prepared by Excel Finance MCP', '', '', '', '', ''],
        ['Date: ' + new Date().toLocaleDateString(), '', '', '', '', ''],
        ['', '', '', '', '', ''],
        ['ASSUMPTIONS:', '', '', '', '', ''],
        ['Discount Rate (WACC):', { formula: `=${discountRate}`, value: null }, 'Cell: B6', 'Formula: User Input', 'Standard: GAAP Cost of Capital', 'Reference: https://www.fasb.org/standards/'],
        ['', '', '', '', '', ''],
        ['CASH FLOW PROJECTION:', '', '', '', '', ''],
        ['Year', 'Cash Flow', 'PV Factor', 'Present Value', 'Cumulative PV', 'Documentation'],
        ['0', { formula: '=C11', value: null }, '1.00', { formula: '=B10*C10', value: null }, { formula: '=D10', value: null }, 'Initial Investment (negative)'],
        ['1', { formula: '=C12', value: null }, { formula: '=1/(1+$B$6)^A11', value: null }, { formula: '=B11*C11', value: null }, { formula: '=E10+D11', value: null }, 'Year 1 net cash flow'],
        ['2', { formula: '=C13', value: null }, { formula: '=1/(1+$B$6)^A12', value: null }, { formula: '=B12*C12', value: null }, { formula: '=E11+D12', value: null }, 'Year 2 net cash flow'],
        ['3', { formula: '=C14', value: null }, { formula: '=1/(1+$B$6)^A13', value: null }, { formula: '=B13*C13', value: null }, { formula: '=E12+D13', value: null }, 'Year 3 net cash flow'],
        ['4', { formula: '=C15', value: null }, { formula: '=1/(1+$B$6)^A14', value: null }, { formula: '=B14*C14', value: null }, { formula: '=E13+D14', value: null }, 'Year 4 net cash flow'],
        ['5', { formula: '=C16', value: null }, { formula: '=1/(1+$B$6)^A15', value: null }, { formula: '=B15*C15', value: null }, { formula: '=E14+D15', value: null }, 'Year 5 net cash flow + terminal value'],
        ['', '', '', '', '', ''],
        ['NET PRESENT VALUE:', { formula: '=SUM(D10:D15)', value: null }, '', 'Formula: =SUM(PresentValues)', 'Standard: FASB Concept 7', 'https://www.fasb.org/concepts/'],
        ['', '', '', '', '', ''],
        ['INVESTMENT DECISION:', '', '', '', '', ''],
        ['NPV Result:', { formula: '=IF(D17>0,"ACCEPT - Positive NPV","REJECT - Negative NPV")', value: '' }, '', 'Accept if NPV > 0', 'GAAP Investment Criteria', ''],
        ['IRR:', { formula: '=IRR(B10:B15)', value: null }, '', 'Compare to discount rate', 'Accept if IRR > WACC', ''],
        ['Profitability Index:', { formula: '=D17/ABS(B10)', value: null }, '', 'PI = NPV / Initial Investment', 'Accept if PI > 1.0', ''],
        ['', '', '', '', '', ''],
        ['INPUT SECTION (Update these cells):', '', '', '', '', ''],
        ['Initial Investment:', { formula: '=-100000', value: null }, '', 'Enter negative amount', '', ''],
        ['Year 1 Cash Flow:', { formula: '=25000', value: null }, '', 'Operating cash flow projection', '', ''],
        ['Year 2 Cash Flow:', { formula: '=30000', value: null }, '', 'Operating cash flow projection', '', ''],
        ['Year 3 Cash Flow:', { formula: '=35000', value: null }, '', 'Operating cash flow projection', '', ''],
        ['Year 4 Cash Flow:', { formula: '=40000', value: null }, '', 'Operating cash flow projection', '', ''],
        ['Year 5 Cash Flow + Terminal:', { formula: '=250000', value: null }, '', 'Final year + terminal value', '', '']
      ]
    };
  }

  static createLoanAnalysisWorksheet(loanAmount: number, annualRate: number, years: number): WorksheetData {
    const monthlyRate = annualRate / 12;
    const totalPayments = years * 12;
    
    return {
      name: 'Loan Analysis',
      data: [
        ['LOAN AMORTIZATION ANALYSIS', '', '', '', '', ''],
        ['Generated by Excel Finance MCP', '', '', '', '', ''],
        ['', '', '', '', '', ''],
        ['LOAN TERMS:', '', '', '', '', ''],
        ['Principal Amount:', { formula: `=${loanAmount}`, value: null }, '', 'User Input', 'GAAP ASC 835-20', 'https://www.fasb.org/asc/835/835-20/'],
        ['Annual Interest Rate:', { formula: `=${annualRate}`, value: null }, '', 'User Input', 'Market Rate', ''],
        ['Loan Term (Years):', { formula: `=${years}`, value: null }, '', 'User Input', '', ''],
        ['Payment Frequency:', 'Monthly', '', 'Standard', '', ''],
        ['', '', '', '', '', ''],
        ['CALCULATED PAYMENT:', '', '', '', '', ''],
        ['Monthly Payment:', { formula: `=PMT(${monthlyRate},${totalPayments},-B5)`, value: null }, '', 'PMT Function', 'Standard Amortization', 'https://www.fasb.org/asc/835/'],
        ['Total Interest:', { formula: `=B11*${totalPayments}-B5`, value: null }, '', 'Total Payments - Principal', '', ''],
        ['Total of Payments:', { formula: `=B11*${totalPayments}`, value: null }, '', 'Payment * Number of Payments', '', ''],
        ['', '', '', '', '', ''],
        ['AMORTIZATION SCHEDULE (First 12 Payments):', '', '', '', '', ''],
        ['Payment #', 'Payment Amount', 'Principal', 'Interest', 'Balance', 'Cumulative Interest'],
        ['0', '', '', '', { formula: `=${loanAmount}`, value: null }, ''],
        
        // Generate first 12 payment rows
        ...Array.from({ length: 12 }, (_, i) => {
          const paymentNum = i + 1;
          return [
            paymentNum,
            { formula: `=$B$11`, value: null },
            { formula: `=$B$11-D${17 + i}`, value: null },
            { formula: `=E${16 + i}*$B$6/12`, value: null },
            { formula: `=E${16 + i}-C${17 + i}`, value: null },
            { formula: `=F${16 + i}+D${17 + i}`, value: null }
          ];
        }),
        
        ['', '', '', '', '', ''],
        ['ANNUAL SUMMARY:', '', '', '', '', ''],
        ['Year 1 Interest:', { formula: '=SUM(D18:D29)', value: null }, '', 'Tax Deductible Interest', 'ASC 835-20-25', ''],
        ['Year 1 Principal:', { formula: '=SUM(C18:C29)', value: null }, '', 'Principal Reduction', '', ''],
        ['', '', '', '', '', ''],
        ['VALIDATION CHECKS:', '', '', '', '', ''],
        ['Payment Calculation:', { formula: '=IF(ABS(B11-PMT(B6/12,B7*12,-B5))<0.01,"CORRECT","ERROR")', value: '' }, '', 'Verify PMT formula', '', ''],
        ['Balance Check:', { formula: '=IF(ABS(E29-(B5-SUM(C18:C29)))<0.01,"CORRECT","ERROR")', value: '' }, '', 'Verify remaining balance', '', ''],
        ['', '', '', '', '', ''],
        ['ACCOUNTING TREATMENT:', '', '', '', '', ''],
        ['Monthly Journal Entry:', '', '', '', '', ''],
        ['  Dr. Interest Expense', { formula: '=D18', value: null }, '', 'Monthly interest portion', '', ''],
        ['  Dr. Loan Principal', { formula: '=C18', value: null }, '', 'Monthly principal portion', '', ''],
        ['  Cr. Cash', { formula: '=B18', value: null }, '', 'Total monthly payment', '', ''],
        ['', '', '', '', '', ''],
        ['References:', '', '', '', '', ''],
        ['- FASB ASC 835: Interest accounting', '', '', '', '', ''],
        ['- FASB ASC 470: Debt classification', '', '', '', '', ''],
        ['- SEC Staff Accounting Bulletin 74', '', '', '', '', '']
      ]
    };
  }

  static createRentRollTemplate(propertyName: string): WorksheetData {
    return {
      name: 'Rent Roll',
      data: [
        ['RENT ROLL ANALYSIS - ' + propertyName.toUpperCase(), '', '', '', '', '', '', '', ''],
        ['As of: ' + new Date().toLocaleDateString(), '', '', '', '', '', '', '', ''],
        ['Generated by Excel Finance MCP', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', ''],
        ['Unit', 'Tenant Name', 'Lease Start', 'Lease End', 'Monthly Rent', 'Security Deposit', 'Status', 'Sq Ft', 'Rent/SF'],
        ['101', 'John Smith', '2024-01-01', '2024-12-31', { formula: '=1500', value: null }, { formula: '=E6*2', value: null }, 'Occupied', { formula: '=850', value: null }, { formula: '=E6/H6', value: null }],
        ['102', 'Jane Doe', '2024-03-01', '2025-02-28', { formula: '=1600', value: null }, { formula: '=E7*2', value: null }, 'Occupied', { formula: '=900', value: null }, { formula: '=E7/H7', value: null }],
        ['103', 'VACANT', '', '', { formula: '=1550', value: null }, { formula: '=0', value: null }, 'Vacant', { formula: '=875', value: null }, { formula: '=IF(H8>0,E8/H8,0)', value: null }],
        ['', '', '', '', '', '', '', '', ''],
        ['SUMMARY ANALYSIS:', '', '', '', '', '', '', '', ''],
        ['Total Units:', { formula: '=COUNTA(A6:A8)', value: null }, '', '', '', '', '', '', ''],
        ['Occupied Units:', { formula: '=COUNTIF(G6:G8,"Occupied")', value: null }, '', '', '', '', '', '', ''],
        ['Vacant Units:', { formula: '=COUNTIF(G6:G8,"Vacant")', value: null }, '', '', '', '', '', '', ''],
        ['Occupancy Rate:', { formula: '=B12/B11*100', value: null }, '%', 'Physical Occupancy', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', ''],
        ['FINANCIAL SUMMARY:', '', '', '', '', '', '', '', ''],
        ['Gross Potential Rent:', { formula: '=SUM(E6:E8)', value: null }, '', 'If 100% occupied', 'ASC 842 Lease Income', '', '', '', ''],
        ['Current Rental Income:', { formula: '=SUMIF(G6:G8,"Occupied",E6:E8)', value: null }, '', 'Actual occupied rent', '', '', '', '', ''],
        ['Vacancy Loss:', { formula: '=B16-B17', value: null }, '', 'Lost rental income', '', '', '', '', ''],
        ['Economic Occupancy:', { formula: '=B17/B16*100', value: null }, '%', 'Revenue-based occupancy', '', '', '', '', ''],
        ['Average Rent per Unit:', { formula: '=B17/B12', value: null }, '', 'Occupied units only', '', '', '', '', ''],
        ['Average Rent per Sq Ft:', { formula: '=SUMPRODUCT(E6:E8,H6:H8)/SUMIF(G6:G8,"Occupied",H6:H8)', value: null }, '', 'Weighted average', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', ''],
        ['LEASE EXPIRATION ANALYSIS:', '', '', '', '', '', '', '', ''],
        ['Next 3 Months:', { formula: '=SUMPRODUCT((D6:D8<=TODAY()+90)*(D6:D8>=TODAY())*(G6:G8="Occupied")*E6:E8)', value: null }, '', 'Expiring rent amount', '', '', '', '', ''],
        ['Next 6 Months:', { formula: '=SUMPRODUCT((D6:D8<=TODAY()+180)*(D6:D8>=TODAY())*(G6:G8="Occupied")*E6:E8)', value: null }, '', 'Expiring rent amount', '', '', '', '', ''],
        ['Next 12 Months:', { formula: '=SUMPRODUCT((D6:D8<=TODAY()+365)*(D6:D8>=TODAY())*(G6:G8="Occupied")*E6:E8)', value: null }, '', 'Expiring rent amount', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', ''],
        ['ACCOUNTING REFERENCES:', '', '', '', '', '', '', '', ''],
        ['- FASB ASC 842: Lease Accounting', '', '', '', '', '', '', '', ''],
        ['- FASB ASC 360: Property, Plant & Equipment', '', '', '', '', '', '', '', ''],
        ['- Real Estate Investment Analysis Standards', '', '', '', '', '', '', '', '']
      ]
    };
  }

  static createFinancialRatiosWorksheet(companyName: string): WorksheetData {
    return {
      name: 'Financial Ratios',
      data: [
        ['FINANCIAL RATIO ANALYSIS - ' + companyName.toUpperCase(), '', '', '', '', ''],
        ['Period Ending: [Enter Date]', '', '', '', '', ''],
        ['Prepared by Excel Finance MCP', '', '', '', '', ''],
        ['', '', '', '', '', ''],
        ['BALANCE SHEET INPUTS:', 'Amount', 'Cell Reference', 'GAAP Standard', 'Notes', ''],
        ['Current Assets', { formula: '=0', value: null }, 'B6', 'ASC 210-10', 'Cash + AR + Inventory + Prepaid', ''],
        ['Total Assets', { formula: '=0', value: null }, 'B7', 'ASC 210-10', 'Current + Non-current assets', ''],
        ['Current Liabilities', { formula: '=0', value: null }, 'B8', 'ASC 210-10', 'Payable within 1 year', ''],
        ['Total Liabilities', { formula: '=0', value: null }, 'B9', 'ASC 470', 'Current + Long-term debt', ''],
        ['Shareholders Equity', { formula: '=0', value: null }, 'B10', 'ASC 505', 'Total equity accounts', ''],
        ['Inventory', { formula: '=0', value: null }, 'B11', 'ASC 330', 'Inventory at cost or market', ''],
        ['Cash & Equivalents', { formula: '=0', value: null }, 'B12', 'ASC 305', 'Highly liquid investments', ''],
        ['', '', '', '', '', ''],
        ['INCOME STATEMENT INPUTS:', 'Amount', 'Cell Reference', 'GAAP Standard', 'Notes', ''],
        ['Revenue', { formula: '=0', value: null }, 'B15', 'ASC 606', 'Total recognized revenue', ''],
        ['Cost of Goods Sold', { formula: '=0', value: null }, 'B16', 'ASC 330', 'Direct costs of revenue', ''],
        ['Operating Income', { formula: '=0', value: null }, 'B17', 'ASC 220', 'Income from operations', ''],
        ['Net Income', { formula: '=0', value: null }, 'B18', 'ASC 220', 'Bottom line earnings', ''],
        ['Interest Expense', { formula: '=0', value: null }, 'B19', 'ASC 835', 'Cost of debt financing', ''],
        ['', '', '', '', '', ''],
        ['CALCULATED RATIOS:', 'Formula', 'Value', 'Benchmark', 'Analysis', 'Reference'],
        ['', '', '', '', '', ''],
        ['LIQUIDITY RATIOS:', '', '', '', '', ''],
        ['Current Ratio', '=B6/B8', { formula: '=B6/B8', value: null }, '1.0 - 3.0', 'Short-term liquidity', 'ASC 210-10'],
        ['Quick Ratio', '=(B6-B11)/B8', { formula: '=(B6-B11)/B8', value: null }, '0.5 - 1.5', 'Immediate liquidity', 'ASC 210-10'],
        ['Cash Ratio', '=B12/B8', { formula: '=B12/B8', value: null }, '0.1 - 0.5', 'Most conservative', 'ASC 305'],
        ['', '', '', '', '', ''],
        ['LEVERAGE RATIOS:', '', '', '', '', ''],
        ['Debt-to-Equity', '=B9/B10', { formula: '=B9/B10', value: null }, '0.3 - 0.6', 'Financial leverage', 'ASC 470'],
        ['Debt-to-Assets', '=B9/B7', { formula: '=B9/B7', value: null }, '0.2 - 0.5', 'Asset financing', 'ASC 470'],
        ['Equity Multiplier', '=B7/B10', { formula: '=B7/B10', value: null }, '1.5 - 3.0', 'Financial leverage', 'ASC 505'],
        ['Interest Coverage', '=B17/B19', { formula: '=B17/B19', value: null }, '> 2.5', 'Debt service ability', 'ASC 835'],
        ['', '', '', '', '', ''],
        ['PROFITABILITY RATIOS:', '', '', '', '', ''],
        ['Gross Margin %', '=(B15-B16)/B15*100', { formula: '=(B15-B16)/B15*100', value: null }, 'Industry Var.', 'Pricing power', 'ASC 606'],
        ['Operating Margin %', '=B17/B15*100', { formula: '=B17/B15*100', value: null }, '5% - 15%', 'Operational efficiency', 'ASC 220'],
        ['Net Margin %', '=B18/B15*100', { formula: '=B18/B15*100', value: null }, '3% - 10%', 'Overall profitability', 'ASC 220'],
        ['Return on Assets %', '=B18/B7*100', { formula: '=B18/B7*100', value: null }, '5% - 20%', 'Asset utilization', 'ROA Analysis'],
        ['Return on Equity %', '=B18/B10*100', { formula: '=B18/B10*100', value: null }, '10% - 25%', 'Shareholder return', 'ROE Analysis'],
        ['', '', '', '', '', ''],
        ['ACTIVITY RATIOS:', '', '', '', '', ''],
        ['Asset Turnover', '=B15/B7', { formula: '=B15/B7', value: null }, '0.5 - 2.0', 'Asset efficiency', 'ASC 210'],
        ['Inventory Turnover', '=B16/B11', { formula: '=B16/B11', value: null }, '4 - 12', 'Inventory management', 'ASC 330'],
        ['DSO (Days Sales Outstanding)', '=(B6-B11-B12)/B15*365', { formula: '=(B6-B11-B12)/B15*365', value: null }, '30 - 60 days', 'Collection efficiency', 'ASC 310'],
        ['', '', '', '', '', ''],
        ['DUPONT ANALYSIS:', '', '', '', '', ''],
        ['ROE Decomposition:', '=C33*C39*C29', { formula: '=C33*C39*C29', value: null }, '', 'Net Margin × Asset Turnover × Equity Multiplier', 'DuPont Framework'],
        ['', '', '', '', '', ''],
        ['RATIO INTERPRETATION:', '', '', '', '', ''],
        ['Overall Liquidity:', { formula: '=IF(C25>1.5,"Strong",IF(C25>1,"Adequate","Weak"))', value: '' }, '', 'Based on current ratio', '', ''],
        ['Financial Risk:', { formula: '=IF(C28<0.4,"Low",IF(C28<0.6,"Moderate","High"))', value: '' }, '', 'Based on debt-to-equity', '', ''],
        ['Profitability Trend:', '[Manual Assessment]', '', 'Compare to prior periods', '', ''],
        ['', '', '', '', '', ''],
        ['PROFESSIONAL REFERENCES:', '', '', '', '', ''],
        ['- FASB Accounting Standards Codification', 'https://www.fasb.org/asc/', '', '', '', ''],
        ['- SEC Accounting Quality and Financial Statements', 'https://www.sec.gov/files/aqfs.pdf', '', '', '', ''],
        ['- AICPA Audit and Accounting Guide', 'https://www.aicpa.org/research/standards', '', '', '', '']
      ]
    };
  }

  static createCashFlowProjectionWorksheet(entityName: string): WorksheetData {
    return {
      name: 'Cash Flow Projection',
      data: [
        ['CASH FLOW PROJECTION - ' + entityName.toUpperCase(), '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['12-Month Rolling Forecast', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['Prepared by Excel Finance MCP', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Total'],
        ['', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['OPERATING CASH FLOWS:', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['Revenue Collections', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B8:M8)', value: null }],
        ['Operating Expenses', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B9:M9)', value: null }],
        ['Payroll & Benefits', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B10:M10)', value: null }],
        ['Rent & Utilities', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B11:M11)', value: null }],
        ['Tax Payments', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B12:M12)', value: null }],
        ['Net Operating Cash Flow', { formula: '=B8-SUM(B9:B12)', value: null }, { formula: '=C8-SUM(C9:C12)', value: null }, 
         { formula: '=D8-SUM(D9:D12)', value: null }, { formula: '=E8-SUM(E9:E12)', value: null }, { formula: '=F8-SUM(F9:F12)', value: null },
         { formula: '=G8-SUM(G9:G12)', value: null }, { formula: '=H8-SUM(H9:H12)', value: null }, { formula: '=I8-SUM(I9:I12)', value: null },
         { formula: '=J8-SUM(J9:J12)', value: null }, { formula: '=K8-SUM(K9:K12)', value: null }, { formula: '=L8-SUM(L9:L12)', value: null },
         { formula: '=M8-SUM(M9:M12)', value: null }, { formula: '=SUM(B13:M13)', value: null }],
        ['', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['INVESTING CASH FLOWS:', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['Capital Expenditures', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B16:M16)', value: null }],
        ['Asset Sales', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B17:M17)', value: null }],
        ['Net Investing Cash Flow', { formula: '=B17-B16', value: null }, { formula: '=C17-C16', value: null }, 
         { formula: '=D17-D16', value: null }, { formula: '=E17-E16', value: null }, { formula: '=F17-F16', value: null },
         { formula: '=G17-G16', value: null }, { formula: '=H17-H16', value: null }, { formula: '=I17-I16', value: null },
         { formula: '=J17-J16', value: null }, { formula: '=K17-K16', value: null }, { formula: '=L17-L16', value: null },
         { formula: '=M17-M16', value: null }, { formula: '=SUM(B18:M18)', value: null }],
        ['', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['FINANCING CASH FLOWS:', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['Loan Proceeds', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B21:M21)', value: null }],
        ['Loan Payments', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B22:M22)', value: null }],
        ['Equity Contributions', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B23:M23)', value: null }],
        ['Dividends Paid', { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=0', value: null }, { formula: '=SUM(B24:M24)', value: null }],
        ['Net Financing Cash Flow', { formula: '=B21-B22+B23-B24', value: null }, { formula: '=C21-C22+C23-C24', value: null },
         { formula: '=D21-D22+D23-D24', value: null }, { formula: '=E21-E22+E23-E24', value: null }, { formula: '=F21-F22+F23-F24', value: null },
         { formula: '=G21-G22+G23-G24', value: null }, { formula: '=H21-H22+H23-H24', value: null }, { formula: '=I21-I22+I23-I24', value: null },
         { formula: '=J21-J22+J23-J24', value: null }, { formula: '=K21-K22+K23-K24', value: null }, { formula: '=L21-L22+L23-L24', value: null },
         { formula: '=M21-M22+M23-M24', value: null }, { formula: '=SUM(B25:M25)', value: null }],
        ['', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['NET CASH FLOW:', { formula: '=B13+B18+B25', value: null }, { formula: '=C13+C18+C25', value: null },
         { formula: '=D13+D18+D25', value: null }, { formula: '=E13+E18+E25', value: null }, { formula: '=F13+F18+F25', value: null },
         { formula: '=G13+G18+G25', value: null }, { formula: '=H13+H18+H25', value: null }, { formula: '=I13+I18+I25', value: null },
         { formula: '=J13+J18+J25', value: null }, { formula: '=K13+K18+K25', value: null }, { formula: '=L13+L18+L25', value: null },
         { formula: '=M13+M18+M25', value: null }, { formula: '=SUM(B27:M27)', value: null }],
        ['', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['CASH BALANCE:', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['Beginning Balance', { formula: '=50000', value: null }, { formula: '=C30', value: null }, { formula: '=D30', value: null }, { formula: '=E30', value: null }, 
         { formula: '=F30', value: null }, { formula: '=G30', value: null }, { formula: '=H30', value: null }, { formula: '=I30', value: null },
         { formula: '=J30', value: null }, { formula: '=K30', value: null }, { formula: '=L30', value: null }, { formula: '=M30', value: null }, ''],
        ['Ending Balance', { formula: '=B29+B27', value: null }, { formula: '=C29+C27', value: null }, { formula: '=D29+D27', value: null },
         { formula: '=E29+E27', value: null }, { formula: '=F29+F27', value: null }, { formula: '=G29+G27', value: null },
         { formula: '=H29+H27', value: null }, { formula: '=I29+I27', value: null }, { formula: '=J29+J27', value: null },
         { formula: '=K29+K27', value: null }, { formula: '=L29+L27', value: null }, { formula: '=M29+M27', value: null }, ''],
        ['', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['CASH FLOW ANALYSIS:', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['Minimum Cash Required:', { formula: '=25000', value: null }, '', 'Safety buffer', '', '', '', '', '', '', '', '', '', ''],
        ['Cash Shortfall Months:', { formula: '=SUMPRODUCT((B30:M30<$B$33)*1)', value: null }, '', 'Months below minimum', '', '', '', '', '', '', '', '', '', ''],
        ['Maximum Cash Balance:', { formula: '=MAX(B30:M30)', value: null }, '', 'Peak cash position', '', '', '', '', '', '', '', '', '', ''],
        ['Average Monthly Balance:', { formula: '=AVERAGE(B30:M30)', value: null }, '', 'Average cash on hand', '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['GAAP REFERENCES:', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['- ASC 230: Statement of Cash Flows', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['- ASC 210: Balance Sheet Classification', '', '', '', '', '', '', '', '', '', '', '', '', ''],
        ['- Working Capital Management Best Practices', '', '', '', '', '', '', '', '', '', '', '', '', '']
      ]
    };
  }
}